let
  # Official Catppuccin colours. Semantic roles keep text readable in both modes.
  mocha = {
    rosewater = "f5e0dc";
    flamingo = "f2cdcd";
    pink = "f5c2e7";
    mauve = "cba6f7";
    red = "f38ba8";
    maroon = "eba0ac";
    peach = "fab387";
    yellow = "f9e2af";
    green = "a6e3a1";
    teal = "94e2d5";
    sky = "89dceb";
    sapphire = "74c7ec";
    blue = "89b4fa";
    lavender = "b4befe";
    text = "cdd6f4";
    subtext1 = "bac2de";
    subtext0 = "a6adc8";
    overlay2 = "9399b2";
    overlay1 = "7f849c";
    overlay0 = "6c7086";
    surface2 = "585b70";
    surface1 = "45475a";
    surface0 = "313244";
    base = "1e1e2e";
    mantle = "181825";
    crust = "11111b";
  };
  latte = {
    rosewater = "dc8a78";
    flamingo = "dd7878";
    pink = "ea76cb";
    mauve = "8839ef";
    red = "d20f39";
    maroon = "e64553";
    peach = "fe640b";
    yellow = "df8e1d";
    green = "40a02b";
    teal = "179299";
    sky = "04a5e5";
    sapphire = "209fb5";
    blue = "1e66f5";
    lavender = "7287fd";
    text = "4c4f69";
    subtext1 = "5c5f77";
    subtext0 = "6c6f85";
    overlay2 = "7c7f93";
    overlay1 = "8c8fa1";
    overlay0 = "9ca0b0";
    surface2 = "acb0be";
    surface1 = "bcc0cc";
    surface0 = "ccd0da";
    base = "eff1f5";
    mantle = "e6e9ef";
    crust = "dce0e8";
  };
  roles =
    p:
    p
    // {
      primary_paletteKeyColor = p.lavender;
      secondary_paletteKeyColor = p.mauve;
      tertiary_paletteKeyColor = p.pink;
      neutral_paletteKeyColor = p.overlay0;
      neutral_variant_paletteKeyColor = p.overlay1;
      background = p.base;
      onBackground = p.text;
      surface = p.base;
      onSurface = p.text;
      surfaceDim = p.mantle;
      surfaceBright = p.surface0;
      surfaceContainerLowest = p.crust;
      surfaceContainerLow = p.mantle;
      surfaceContainer = p.surface0;
      surfaceContainerHigh = p.surface1;
      surfaceContainerHighest = p.surface2;
      surfaceVariant = p.surface0;
      onSurfaceVariant = p.subtext1;
      inverseSurface = p.text;
      inverseOnSurface = p.base;
      outline = p.overlay0;
      outlineVariant = p.surface1;
      shadow = "000000";
      scrim = "000000";
      surfaceTint = p.lavender;
      primary = p.lavender;
      # Lavender in Latte needs dark text, rather than Latte's pale crust.
      onPrimary = mocha.crust;
      primaryContainer = p.surface0;
      onPrimaryContainer = p.text;
      inversePrimary = p.lavender;
      secondary = p.mauve;
      onSecondary = if p == latte then "ffffff" else p.crust;
      secondaryContainer = p.surface0;
      onSecondaryContainer = p.text;
      tertiary = p.pink;
      onTertiary = mocha.crust;
      tertiaryContainer = p.surface0;
      onTertiaryContainer = p.text;
      error = p.red;
      onError = if p == latte then "ffffff" else p.crust;
      errorContainer = p.surface0;
      onErrorContainer = p.red;
      primaryFixed = p.lavender;
      primaryFixedDim = p.lavender;
      onPrimaryFixed = mocha.crust;
      onPrimaryFixedVariant = mocha.crust;
      secondaryFixed = p.mauve;
      secondaryFixedDim = p.mauve;
      onSecondaryFixed = if p == latte then "ffffff" else p.crust;
      onSecondaryFixedVariant = if p == latte then "ffffff" else p.crust;
      tertiaryFixed = p.pink;
      tertiaryFixedDim = p.pink;
      onTertiaryFixed = mocha.crust;
      onTertiaryFixedVariant = mocha.crust;
      term0 = p.surface1;
      term1 = p.red;
      term2 = p.green;
      term3 = p.yellow;
      term4 = p.blue;
      term5 = p.pink;
      term6 = p.teal;
      term7 = p.subtext1;
      term8 = p.surface2;
      term9 = p.red;
      term10 = p.green;
      term11 = p.yellow;
      term12 = p.blue;
      term13 = p.pink;
      term14 = p.teal;
      term15 = p.text;
    };
in
{
  inherit mocha latte;
  dark = roles mocha;
  light = roles latte;
}
